### ISSUE TITLE
Pretty output

### ISSUE THREAD

**Issue by kvz** [freyproject/frey#50]
Does ansible support more structured output so a machine could easily read/parse what's going on?

If so, I'm thinking if we should change the output so that Frey just says:

```
--> Install: <this changes with what's being worked on, e.g. Common | apt update >
--> Setup: <this changes with what's being worked on>
--> Restart:

An error happened, so now we see the full output of this step
```

We should also consider agreeing to a convention for naming tasks, so that they are consistent across all bundled roles and inline Freyfile tasks

Thoughts?

**Comment by tersmitten** [comment]
I think this is possible using an Ansible callack plugin.

Naming tasks consistently is nice to have, but probably a lot of work especially if you start including more roles

**Comment by kvz** [comment]
Yeah, perhaps if we can just report sth like:

`<frey step><hostname><role name || "inline"><task name || action || module> <rotating last stdout || stderr line>`

that would be quite cool!

**Comment by kvz** [comment]
https://www.npmjs.com/package/log-update

**Comment by kvz** [comment]
This is ready for shipping in upcoming release
